spring:
  profiles:
    active: dev  # Cambiare con(ema-gio-luca)

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # "create-drop" è rischioso perché cancella i dati ad ogni avvio
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
